title: "Wave Watch 3"
description: "20 year global ocean surface wave hindcast provided by Ifremer (French Research Institute for Exploitation of the Sea)"
recipes:
  - id: "wavewatch3"
    object: "recipe:WW3"
provenance:
  providers:
    - name: "Ifremer"
      description: "Ifremer"
      roles:
        - host
      url: https://www.ifremer.fr/en
  license: "TBW"
